package no.nav.foreldrepenger.info.felles.datatyper;

public enum BehandlingResultatType {
    IKKE_FASTSATT("IKKE_FASTSATT"), //$NON-NLS-1$
    INNVILGET("INNVILGET"), //$NON-NLS-1$
    AVSLÅTT("AVSLÅTT"), //$NON-NLS-1$
    OPPHØR("OPPHØR"), //$NON-NLS-1$
    HENLAGT_SØKNAD_TRUKKET("HENLAGT_SØKNAD_TRUKKET"), //$NON-NLS-1$
    HENLAGT_FEILOPPRETTET("HENLAGT_FEILOPPRETTET"), //$NON-NLS-1$
    HENLAGT_BRUKER_DØD("HENLAGT_BRUKER_DØD"), //$NON-NLS-1$
    MERGET_OG_HENLAGT("MERGET_OG_HENLAGT"), //$NON-NLS-1$
    HENLAGT_SØKNAD_MANGLER("HENLAGT_SØKNAD_MANGLER"), //$NON-NLS-1$
    FORELDREPENGER_ENDRET("FORELDREPENGER_ENDRET"), //$NON-NLS-1$
    INGEN_ENDRING("INGEN_ENDRING"), //$NON-NLS-1$
    
    KLAGE_AVVIST("KLAGE_AVVIST"), //$NON-NLS-1$
    KLAGE_MEDHOLD("KLAGE_MEDHOLD"), //$NON-NLS-1$
    KLAGE_YTELSESVEDTAK_OPPHEVET("KLAGE_YTELSESVEDTAK_OPPHEVET"), //$NON-NLS-1$
    KLAGE_YTELSESVEDTAK_STADFESTET("KLAGE_YTELSESVEDTAK_STADFESTET"), //$NON-NLS-1$
    HENLAGT_KLAGE_TRUKKET("HENLAGT_KLAGE_TRUKKET"), //$NON-NLS-1$

    INNSYN_INNVILGET("INNSYN_INNVILGET"), //$NON-NLS-1$
    INNSYN_DELVIS_INNVILGET("INNSYN_DELVIS_INNVILGET"), //$NON-NLS-1$
    INNSYN_AVVIST("INNSYN_AVVIST"); //$NON-NLS-1$

    private String verdi;

    BehandlingResultatType(String verdi) {
        this.verdi = verdi;
    }

    public String getVerdi() {
        return verdi;
    }
}
