package no.nav.foreldrepenger.info.felles.datatyper;

public enum BehandlingÅrsak {
    HENDELSE_FØDSEL("RE-HENDELSE-FØDSEL"), //$NON-NLS-1$
    MANGLENDE_FØDSEL("RE-MF"), //$NON-NLS-1$
    MANGLENDE_FØDSEL_TERMIN("RE-MFIP"), //$NON-NLS-1$
    ULIKT_ANTALL_BARN("RE-AVAB"), //$NON-NLS-1$
    FEIL_LOVANVENDELSE("RE-LOV"), //$NON-NLS-1$
    FEIL_REGELVERKSFORSTÅELSE("RE-RGLF"), //$NON-NLS-1$
    FEIL_ELLER_ENDRET_FAKTA("RE-FEFAKTA"), //$NON-NLS-1$
    PROSESSURELL_FEIL("RE-PRSSL"), //$NON-NLS-1$
    ETTER_KLAGE("ETTER_KLAGE"), //$NON-NLS-1$
    ENDRING_FRA_BRUKER("RE-END-FRA-BRUKER"), //$NON-NLS-1$
    ENDRET_INNTEKTSMELDING("RE-END-INNTEKTSMELD"), //$NON-NLS-1$
    KØET_BEHANDLING("KØET_BEHANDLING"), //$NON-NLS-1$
    BERØRT_BEHANDLING("BERØRT_BEHANDLING"), //$NON-NLS-1$
    REGISTER_OPPLYSNING("RE-REGISTEROPPL"), //$NON-NLS-1$
    YTELSE("RE-YTELSE"), //$NON-NLS-1$
    KLAGE("RE-KLAG"), //$NON-NLS-1$
    MEDLEMSKAP("RE-MDL"), //$NON-NLS-1$
    OPPTJENING("RE-OPTJ"), //$NON-NLS-1$
    FORDELING_STØNADSPERIODE("RE-FRDLING"), //$NON-NLS-1$
    INNTEKT("RE-INNTK"), //$NON-NLS-1$
    DØD("RE-DØD"), //$NON-NLS-1$
    RELASJON_TIL_BARNET("RE-SRTB"), //$NON-NLS-1$
    SØKNADSFRIST("RE-FRIST"), //$NON-NLS-1$
    BEREGNINGSGRUNNLAG("RE-BER-GRUN"), //$NON-NLS-1$
    TILSTØTENDE_YTELSE_INNVILGET("RE-TILST-YT-INNVIL"), //$NON-NLS-1$
    ENDRING_BEREGNINGSGRUNNLAG("RE-ENDR-BER-GRUN"), //$NON-NLS-1$
    TILSTØTENDE_YTELSE_OPPHØRT("RE-TILST-YT-OPPH"), //$NON-NLS-1$
    ANNET("RE-ANNET");  //$NON-NLS-1$

    private String verdi;

    BehandlingÅrsak(String verdi) {
        this.verdi = verdi;
    }

    public String getVerdi() {
        return verdi;
    }
}
