package no.nav.foreldrepenger.info.felles.datatyper;

public enum BehandlingResultatType {
    IKKE_FASTSATT("IKKE_FASTSATT"),
    INNVILGET("INNVILGET"),
    AVSLÅTT("AVSLÅTT"),
    OPPHØR("OPPHØR"),
    HENLAGT_SØKNAD_TRUKKET("HENLAGT_SØKNAD_TRUKKET"),
    HENLAGT_FEILOPPRETTET("HENLAGT_FEILOPPRETTET"),
    HENLAGT_BRUKER_DØD("HENLAGT_BRUKER_DØD"),
    MERGET_OG_HENLAGT("MERGET_OG_HENLAGT"),
    HENLAGT_SØKNAD_MANGLER("HENLAGT_SØKNAD_MANGLER"),
    FORELDREPENGER_ENDRET("FORELDREPENGER_ENDRET"),
    INGEN_ENDRING("INGEN_ENDRING"),

    KLAGE_AVVIST("KLAGE_AVVIST"),
    KLAGE_MEDHOLD("KLAGE_MEDHOLD"),
    KLAGE_YTELSESVEDTAK_OPPHEVET("KLAGE_YTELSESVEDTAK_OPPHEVET"),
    KLAGE_YTELSESVEDTAK_STADFESTET("KLAGE_YTELSESVEDTAK_STADFESTET"),
    HENLAGT_KLAGE_TRUKKET("HENLAGT_KLAGE_TRUKKET"),

    INNSYN_INNVILGET("INNSYN_INNVILGET"),
    INNSYN_DELVIS_INNVILGET("INNSYN_DELVIS_INNVILGET"),
    INNSYN_AVVIST("INNSYN_AVVIST");

    private final String verdi;

    BehandlingResultatType(String verdi) {
        this.verdi = verdi;
    }

    public String getVerdi() {
        return verdi;
    }
}
