CREATE OR REPLACE VIEW AKSJONSPUNKT
  AS SELECT DISTINCT
         aks.ID AS AKSJONSPUNKT_ID,
         aks.AKSJONSPUNKT_STATUS AS AKSJONSPUNKT_STATUS,
         aks.AKSJONSPUNKT_DEF AS AKSJONSPUNKT_DEF,
         aks.FRIST_TID AS FRIST_TID,
         aks.BEHANDLING_ID AS BEHANDLING_ID,
         aks.OPPRETTET_AV AS OPPRETTET_AV,
         aks.OPPRETTET_TID AS OPPRETTET_TID,
         aks.ENDRET_AV AS ENDRET_AV,
         aks.ENDRET_TID AS ENDRET_TID
     FROM
          ${fpinfo.fpsak.schema.navn}.AKSJONSPUNKT aks;

GRANT SELECT ON AKSJONSPUNKT TO ${fpinfo.schema.navn};
