CREATE
OR REPLACE VIEW AKSJONSPUNKT
  AS
SELECT aks.ID                  AS ID
     , aks.AKSJONSPUNKT_STATUS AS STATUS
     , aks.AKSJONSPUNKT_DEF    AS DEFINISJON
     , aks.VENT_AARSAK         AS VENT_AARSAK
     , aks.BEHANDLING_ID       AS BEHANDLING_ID
FROM fpsak.AKSJONSPUNKT aks;

GRANT SELECT ON AKSJONSPUNKT TO fpinfo;
