kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: fpinfo
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: fpsoknad-mottak
  env:
{{#each env}}
   - name: {{@key}}
     value: "{{this}}"
{{/each}}
  image: {{image}}
  ingresses:
{{#each ingresses as |url|}}
    - {{url}}
{{/each}}
  port: 8080
  liveness:
    path: /fpinfo/internal/health/isAlive
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  prometheus:
    enabled: true
    path: /fpinfo/internal/metrics/prometheus
  readiness:
    path: /fpinfo/internal/health/isReady
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  replicas:
    min: 3
    max: 3
    cpuThresholdPercentage: 80
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 256Mi
  vault:
    enabled: true
    paths:

    - kvPath: {{oraclefpinfocredsskv}}
      mountPath: /var/run/secrets/nais.io/fpinfoSchema

    - kvPath: {{serviceuserkv}}
      mountPath: /var/run/secrets/nais.io/srvfpinfo

    - kvPath: /kv/{{cluster}}/fss/fpinfo/{{namespace}}
      mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
